<!-- wp:wsutheme/global-header /-->
<!-- wp:wsutheme/site-header /-->
<!-- wp:wsutheme/quicklinks /-->
<!-- wp:wsutheme/navigation-mobile /-->
<!-- wp:wsutheme/navigation-horizontal /-->
<!-- wp:wsutheme/navigation-vertical /-->
<!-- wp:wsutheme/wrapper-site -->
    <!-- wp:wsutheme/navigation-audience /-->
    <!-- wp:wsutheme/wrapper-content -->
        <!-- wp:wsutheme/wrapper-main -->
            <!-- wp:wsutheme/posts {"style":"page"} -->
            <!-- /wp:wsutheme/posts -->
        <!-- /wp:wsutheme/wrapper-main -->
    <!-- /wp:wsutheme/wrapper-content -->
    <!-- wp:wsutheme/site-footer -->
        <!-- wp:wsutheme/site-social /-->
        <!-- wp:wsutheme/site-contact /-->
    <!-- /wp:wsutheme/site-footer -->
<!-- /wp:wsutheme/wrapper-site -->
<!-- wp:wsutheme/global-footer /-->